# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NU8TYN77S29jfXoOlls2uNlu0RwZZQii
"""

import pandas as pd
baza={
    "Fish":[ "Qambarov Samandar" , "Qambarova Mashura" , "Toshiboyev Alijon", "Holiqova Rano" , "Soliyev Sardor" , "Qochqorova Oydinoy" , "Qosimov Muhridin" ,
            "Qosimova Mohinur" , "Holdarov Riqistilo" , "Holdarova Oydinoy" ],
    "Yosh":[ "18" , "18" , "11" , "22" , "55" , "88" , "32" , "11" , "44" , "43" ],
    "Maktabi":[ "41-maktab" , " 42-maktab" , "71-maktab" , "91-maktab" , "61-maktab" , "31-maktab" , "51-maktab" , "81-maktab" , "21-maktab" , "11-maktab" ],
    "Jinsi":[  'erkak' , 'ayol' , 'erkak' , 'ayol' , 'erkak' , 'ayol' , 'erkak' , 'ayol' , 'erkak' , 'ayol' ],
    "Manzili":[  "Andijon shaxar" , "Andijon shaxar" , "Qashqadaryo shaxar" , "Xorazim shaxar" , "Jizah shaxar" , "Surhandaryo shaxar"
    , "Sirdaryo shaxar" , "Buhoro shaxar" , "Toshkent shaxar" , "Namangan shaxar" ]
}

malumot=pd.DataFrame(baza)
print(malumot)

filtr=malumot[malumot['Jinsi']=='ayol']
print(filtr)

filtr=malumot[(malumot['Jinsi']=='erkak') & (malumot['Manzili']=='Andijon shaxar')]
print(filtr)